INSERT INTO USER_DETAIL values ('deb.sen93@gmail.com','deba','password','Debapriya','Sen','Y','ROLE_USER');
INSERT INTO USER_DETAIL values('biswa.sen@gmail.com','biswa','password','Biswapriya','Sen','Y','ROLE_ADMIN');

INSERT INTO DEVICE_DETAIL(SERIAL_NUMBER,DEVICE_NAME,MODEL_NUMBER,RELAY1,RELAY2,RELAY3,RELAY4,USER_EMAIL_ID) values ('312312','Tesla-GSM','T-201','Y','N','N','N','deb.sen93@gmail.com');
INSERT INTO DEVICE_DETAIL(SERIAL_NUMBER,DEVICE_NAME,MODEL_NUMBER,RELAY1,RELAY2,RELAY3,RELAY4,USER_EMAIL_ID) values ('312313','Basic-GSM','B-201','N','N','N','N','biswa.sen@gmail.com');
INSERT INTO DEVICE_DETAIL(SERIAL_NUMBER,DEVICE_NAME,MODEL_NUMBER,RELAY1,RELAY2,RELAY3,RELAY4) values ('312314','Basic-GSM','B-201','N','N','N','N');

