INSERT INTO USER_DETAIL values ('deb.sen93@gmail.com','deba','password','Debapriya','Sen','Y','ROLE_USER');
INSERT INTO USER_DETAIL values('biswa.sen@gmail.com','biswa','password','Biswapriya','Sen','Y','ROLE_ADMIN');

INSERT INTO DEVICE_DETAIL(SERIAL_NUMBER,DEVICE_NAME,MODEL_NUMBER,RELAY,DEVICE_RELAY,USER_EMAIL_ID,SECURITY_KEY) values ('312312','Tesla-GSM','T-201','Y','Y','deb.sen93@gmail.com','acee9');
INSERT INTO DEVICE_DETAIL(SERIAL_NUMBER,DEVICE_NAME,MODEL_NUMBER,RELAY,DEVICE_RELAY,USER_EMAIL_ID,SECURITY_KEY) values ('312313','Basic-GSM','B-201','N','Y','biswa.sen@gmail.com','0c59f');
INSERT INTO DEVICE_DETAIL(SERIAL_NUMBER,DEVICE_NAME,MODEL_NUMBER,RELAY,DEVICE_RELAY) values ('312314','Basic-GSM','B-201','N','N');

INSERT INTO SENSOR_DETAIL(ADDRESS,VALUE,DEVICE_ID) values (40001,'KTPM',1);
INSERT INTO SENSOR_DETAIL(ADDRESS,VALUE,DEVICE_ID) values (40002,'VOILA',1);
INSERT INTO SENSOR_DETAIL(ADDRESS,VALUE,DEVICE_ID) values (60001,'UREKA',1);
INSERT INTO SENSOR_DETAIL(ADDRESS,VALUE,DEVICE_ID) values (60002,'KTPM',1);
INSERT INTO SENSOR_DETAIL(ADDRESS,VALUE,DEVICE_ID) values (60003,'YO',2);