create table USER_DETAIL (
EMAIL_ID VARCHAR(100) PRIMARY KEY,
USER_NAME VARCHAR(20) UNIQUE,
PASSWORD VARCHAR(20),
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
ACTIVE BOOLEAN DEFAULT 'Y',
ROLE VARCHAR(10),
);

create table DEVICE_DETAIL(
DEVICE_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
SERIAL_NUMBER VARCHAR(50),
DEVICE_NAME VARCHAR(50),
MODEL_NUMBER VARCHAR(50),
RELAY BOOLEAN DEFAULT 'N',
DEVICE_RELAY BOOLEAN DEFAULT 'N',
DEVICE_FEEDBACK_RELAY BOOLEAN DEFAULT 'N',
USER_EMAIL_ID VARCHAR(100),
SECURITY_KEY VARCHAR(50),
FOREIGN KEY (USER_EMAIL_ID) REFERENCES USER_DETAIL(EMAIL_ID)
);

create table SENSOR_DETAIL(
ID BIGINT PRIMARY KEY AUTO_INCREMENT,
ADDRESS INT,
VALUE VARCHAR(10),
DEVICE_ID BIGINT,
LAST_UPDATED VARCHAR(20),
FOREIGN KEY (DEVICE_ID) REFERENCES DEVICE_DETAIL(DEVICE_ID)
);
